name: observable
version: 0.22.4-dev
author: Dart Team <misc@dartlang.org>
description: Support for marking objects as observable
homepage: https://github.com/google/observable
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  collection: ^1.11.0
  dart_internal: ">0.1.10 < 0.3.0"
  meta: ^1.0.4
  quiver: ^3.0.0

dev_dependencies:
  build_runner: '>=0.8.0 <2.0.0'
  build_test: ^2.0.0
  build_web_compilers: '>=0.3.1 <3.0.0'
  dart_style: ^2.0.0
  pedantic: ^1.4.0
  test: ^1.3.0
